### ISSUE TITLE
Legg til støtte for at bruker får rdf-representasjon for dataservices

### ISSUE THREAD

**Issue by stigbd** [Informasjonsforvaltning/fdk-nginx-search#56]
Analogt som for dataset:
```
curl -H "Accept: text/turtle" https://data.norge.no/dataservices/4526f8f3-4f3b-3633-807c-94fa60f53a11
```
Skal gi 200 OK og rdf (turtle) i respons.

Representasjonen er tilgjengeleg her:
`https://dataservices.fellesdatakatalog.digdir.no/dataservices/4526f8f3-4f3b-3633-807c-94fa60f53a11`

**Comment by valosnah** [comment]
`$ curl -H "Accept: text/turtle" https://staging.fellesdatakatalog.digdir.no/dataservices/f188449a-7624-34f3-b088-88a0662ba1b6`

 

> % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
> 100  1092  100  1092    0     0  12551      0 --:--:-- --:--:-- --:--:-- 12551@prefix dcat:  <http://www.w3.org/ns/dcat#> .
> @prefix dct:   <http://purl.org/dc/terms/> .
> @prefix foaf:  <http://xmlns.com/foaf/0.1/> .
> @prefix rdf:   <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
> @prefix vcard: <http://www.w3.org/2006/vcard/ns#> .
> 
> <https://dataservice-catalog.staging.fellesdatakatalog.digdir.no/data-services/5ea2d75a41c98c4916b70059>
>         rdf:type           dcat:DataService ;
>         dct:description    "This is a sample server Petstore server.  You can find out more about Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).  For this sample, you can use the api key `special-key` to test the authorization filters."@nb ;
>         dct:license        <http://www.apache.org/licenses/LICENSE-2.0.html> ;
>         dct:title          "Swagger Petstore"@nb ;
>         dcat:contactPoint  [ rdf:type        vcard:Organization ;
>                              vcard:fn        "Contact information | (910244132)" ;
>                              vcard:hasEmail  <mailto:apiteam@swagger.io>
>                            ] .
