### ISSUE TITLE
Legg til støtte for at bruker får json-representasjon for dataservices

### ISSUE THREAD

**Issue by stigbd** [Informasjonsforvaltning/fdk-nginx-search#57]
Analogt som for dataset:
```
curl -H "Accept: application/json" https://data.norge.no/dataservices/4526f8f3-4f3b-3633-807c-94fa60f53a11
```
Skal gi 200 OK og json i respons.

Representasjonen skal bli tilgjengeleg frå fdk-harvester-bff. 

Avhenger av https://github.com/Informasjonsforvaltning/fdk-harvester-bff/issues/33

**Comment by valosnah** [comment]
Denne ble fikset av https://github.com/Informasjonsforvaltning/fdk-nginx-search/pull/64 , men ser jeg bare lukket issuet som gjaldt RDF
